# Generated by Django 4.0.5 on 2022-07-11 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published_at')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Other', 'Other')], default='User', max_length=225, verbose_name='user_type')),
                ('device_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='device')),
                ('notification_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='notification_token')),
                ('uniqe_device_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='uniqe_device')),
                ('client_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='client_version')),
                ('server_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='server_version')),
                ('refresh_has_token', models.CharField(blank=True, max_length=225, null=True, verbose_name='refresh_token')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('is_blooked', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
    ]
